" Use vim defaults instead of vi compatibility
set nocompatible

set background=dark
set number
set ruler
set nowrap
set cursorline
set visualbell
set title
set colorcolumn=120

" Reload files changed outside vim
set autoread

" Always save on file
set backupcopy=yes

set history=10000
" Show incomplete commands
set showcmd

set incsearch
" Make search case insensitive
set ignorecase
" unless there's a capital letter
set smartcase

set clipboard=unnamedplus

syntax on

set tabstop=2 shiftwidth=2 expandtab
set autoindent

" save swaps in fixed directories
set directory=~/.vim/tmp/swap//,/var/tmp//,/tmp//

" Trim trailing whitespace on save
autocmd BufWritePre * %s/\s\+$//e

if (has("termguicolors"))
  set termguicolors
endif
colorscheme OceanicNext

let g:netrw_liststyle = 3
let g:netrw_banner = 0
let g:netrw_winsize = 25
let g:netrw_browse_split = 2

set wildmenu
set wildmode=longest:full,full
set wildignore+=*.bmp,*.gif,*.ico,*.jpg,*.png,*.ico
set wildignore+=*.pdf,*.psd
set wildignore+=*.log
set wildignore+=**/node_modules/**,**/.git/**,**/tmp/cache/**,node_modules/**
set wildignore+=*.d.ts,*.d.ts.map,*.test.tsx.snap,*.ts.html

" Remove gvim toolbar
set guioptions-=T
" Remove gvim menubar
set guioptions-=m

set guifont=DejaVu\ Sans\ Mono\ 13

" Golang
let g:go_fmt_command = "goimports"
" let g:go_auto_type_info = 1
autocmd FileType go nnoremap <silent> gr :GoReferrers<CR>

" Enable rufo (RUby FOrmat)
let g:rufo_auto_formatting = 1

" vim-jsx-typescript
" set filetypes as typescriptreact
autocmd BufNewFile,BufRead *.tsx,*.jsx set filetype=typescriptreact

" ALE
let js_fixers = ['prettier', 'eslint']
let g:ale_fixers = {
\   'javascript': js_fixers,
\   'typescript': js_fixers,
\   'typescriptreact': js_fixers,
\   'css': ['prettier'],
\   'scss': ['prettier'],
\   'json': ['prettier'],
\   'md': ['prettier'],
\}
let g:ale_fix_on_save = 1
nnoremap <silent> gr :ALEFindReferences<CR>

autocmd FileType javascript map <buffer> gd :ALEGoToDefinition<CR>
autocmd FileType typescript map <buffer> gd :ALEGoToDefinition<CR>
autocmd FileType typescriptreact map <buffer> gd :ALEGoToDefinition<CR>


" More natural split opening
set splitbelow
set splitright

" Enable project specific vimlocal
set exrc

let mapleader=","
nnoremap <Leader>e :e **/*
nnoremap <Leader>v :vsplit **/*

" Prevent unsafe commands - Must be at the bottom
set secure
